### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Mu7aMNaD** [dfrnoch/nitro-sniper-old#1]
When i send a url that is https://discord.com/gifts/thecode it do nothing.
And the same with https://discordapp.com/gifts/thecode it do nothing.

Only the https://discord.gits/gifts/thecode. Works

can you explain a little how the code blow works.

var gift = /discord\.(gift)|discordapp\.com\/(gift)\/.+[a-z]/

**Comment by Mu7aMNaD** [comment]
Hello, lnxcz can you see this ?

**Comment by 1lix** [comment]
Same for me... it works only with urls with discord.gits/okok

**Comment by dfrnoch** [comment]
I will rewrite it today in python. It will have nitro sniper, giveaway sniper and windows notification.

**Comment by dfrnoch** [comment]
Ok, last few edits and it will be published.. Every link will now work.
